# Generated by Django 4.2.4 on 2024-02-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("cnic", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("cnic_upload", models.ImageField(upload_to="uploads/cnic")),
                ("ssc_obtained", models.IntegerField()),
                ("ssc_total", models.IntegerField()),
                ("ssc_passing_year", models.IntegerField()),
                ("ssc_board", models.CharField(max_length=50)),
                ("ssc_roll_no", models.IntegerField()),
                ("ssc_upload", models.ImageField(upload_to="uploads/ssc")),
                ("fsc_obtained", models.IntegerField()),
                ("fsc_total", models.IntegerField()),
                ("fsc_passing_year", models.IntegerField()),
                ("fsc_board", models.CharField(max_length=50)),
                ("fsc_roll_no", models.IntegerField()),
                ("fsc_upload", models.ImageField(upload_to="uploads/fsc")),
            ],
        ),
    ]
