# Generated by Django 4.2.4 on 2024-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldetail",
            name="cnic_upload",
            field=models.ImageField(upload_to="backend/uploads/cnic"),
        ),
        migrations.AlterField(
            model_name="personaldetail",
            name="fsc_upload",
            field=models.ImageField(upload_to="backend/uploads/fsc"),
        ),
        migrations.AlterField(
            model_name="personaldetail",
            name="ssc_upload",
            field=models.ImageField(upload_to="backend/uploads/ssc"),
        ),
    ]
