# Generated by Django 4.2.4 on 2024-05-17 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_personaldetail_fsc_board_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaldetail",
            name="gender",
        ),
    ]
